# Generated by Django 3.1.1 on 2020-09-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
