# Generated by Django 3.1.1 on 2020-10-01 01:44

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200928_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_timestamp']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_timestamp']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenttimestamp',
            new_name='comment_timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='post_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Date Joined'),
        ),
    ]
