# Generated by Django 3.1.1 on 2020-10-01 23:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=1425807672368, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Posted Date'),
        ),
    ]
