# Generated by Django 3.1.1 on 2020-10-04 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201003_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=1589121802992, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
    ]
