# Generated by Django 3.1.1 on 2020-10-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201004_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=2160905630064, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
    ]
