# Generated by Django 3.1.1 on 2020-10-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201001_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=2420232743056, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
    ]
